### ISSUE TITLE
How to import Your plugin ?

### ISSUE THREAD

**Issue by pragmaticadam** [trufflesuite/drizzle-vue-plugin#11]
Hi, I've tried to import Your plugin in vue

In my package.json I have:

```

  "dependencies": {
    "@drizzle/vue-plugin": "github:trufflesuite/drizzle-vue-plugin",

```

in my main.js I have:

`
  import drizzleVuePlugin from '@drizzle/vue-plugin'
`

I see folder 

mode_modules/@drizzle/vue-plugin in my project structure

still when calling 

  `npm run dev (truffle webpack box)`

I get:

  This dependency was not found:

  * @drizzle/vue-plugin in ./src/main.js

**Comment by cds-amal** [comment]
Thanks for your interest @pragmaticadam!

This plugin is a work in progress and we'll be releasing as a beta product soon. 

Until it is released, you can include it your project like this:

```
  "dependencies": {
    "@drizzle/vue-plugin": "github:trufflesuite/drizzle-vue-plugin#8d257240b852d91d36d05ad26a25909358ad050c",
    "drizzle": "^1.4.0",
    ...
  }
```
